### ISSUE TITLE
404 when trying to use action on windows

### ISSUE THREAD

**Issue by danto7** [jdx/mise-action#114]
I just added a matrix job to one of my private repositorys and stumbeled about a 404 for the mise package on windows:
<img width="1164" alt="Screenshot 2024-08-16 at 17 23 48" src="https://github.com/user-attachments/assets/91542ef6-607c-416a-8325-e1e5b78e24e2">

This is my github action workflow:
```yaml
name: run go tests
on: push
jobs:
  test:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            cache_path: |
              ~/.cache/go-build
              ~/go/pkg/mod
          - name: macos-latest
            cache_path: |
              ~/Library/Caches/go-build
              ~/go/pkg/mod
          - name: windows-latest
            cache_path: |
              ~\AppData\Local\go-build
              ~\go\pkg\mod
    runs-on: ${{ matrix.os.name }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: jdx/mise-action@v2
        with:
          version: 2024.8.6
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.os.cache_path }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: task test
```

I have also tried it without the version variable (so with the latest). Same result. Macos and Ubuntu work fine.
Thanks for the wonderful project :)
