### ISSUE TITLE
Cannot use ubi backend if ubi installed via mise

### ISSUE THREAD

**Issue by glasser** [jdx/mise-action#127]
With this `.mise.toml`:

```
[tools]
rust = "1.81.0"
"cargo:ubi-cli" = "0.2.0"
"ubi:bep/s3deploy" = "v2.3.2"
```

and these steps:

```
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true  # for ubi backend
```

this action successfully installs rust and ubi, but fails to find ubi to use it:

```
     Compiling ubi-cli v0.2.0
      Finished `release` profile [optimized] target(s) in 1m 13s
    Installing /home/runner/.local/share/mise/installs/cargo-ubi-cli/0.2.0/bin/ubi
     Installed package `ubi-cli v0.2.0` (executable `ubi`)
  warning: be sure to add `/home/runner/.local/share/mise/installs/cargo-ubi-cli/0.2.0/bin` to your PATH to be able to run the installed binaries
  mise cargo:ubi-cli@0.2.0 ✓ installed
  mise failed to execute command: ubi --in /home/runner/.local/share/mise/installs/ubi-bep-s3deploy/v2.3.2/bin --project bep/s3deploy --tag v2.3.2
  mise No such file or directory (os error 2)
  mise Run with --verbose or MISE_VERBOSE=1 for more information
```

I'm actually a little surprised that mise understood to use the newly-installed rust for cargo, but not to use the newly-installed ubi.
