### ISSUE TITLE
cache_save option

### ISSUE THREAD

**Issue by julien-carsique-sonarsource** [jdx/mise-action#130]
Hello,
I tried using the cache_save option to save only from the default branch, but the cache is still saved from a pull-request workflow.

```yaml
      - uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2.1.0
        with:
          cache_save: ${{ github.ref_name == github.event.repository.default_branch }}
```

```
Run jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3
  with:
    cache_save: false
    install: true
    cache: true
    cache_key_prefix: mise-v0
    experimental: false
    log_level: info
Restoring mise cache
  mise cache not found for mise-v0-linux-x64-b803ca...
```

```
Post Run jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/... --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~51 MB (53443973 B)
Cache saved successfully
Cache saved from /home/runner/.local/share/mise with key: mise-v0-linux-x64-b803ca...
```
