### ISSUE TITLE
mise ERROR lockfile is experimental. Enable it with `mise settings set experimental true`

### ISSUE THREAD

**Issue by BeyondEvil** [jdx/mise-action#145]
Unclear why I'm getting this error as `experimental` is set to `false`, and I've not provided any lock-files.

Output from Github Actions:

```

Run jdx/mise-action@v2
  with:
    install: true
    cache: true
    cache_save: true
    cache_key_prefix: mise-v0
    experimental: false
    log_level: info
Restoring mise cache
  mise cache not found for mise-v0-linux-x64-a70cbb5df0636947650ad09ccab3705fcee8dc6a37c71b0d4b4e83a6fa39f1d9
Setup mise
  /usr/bin/curl --compressed -fsSL https://mise.jdx.dev/mise-latest-linux-x64 --output /home/runner/.local/share/mise/bin/mise
  /usr/bin/chmod +x /home/runner/.local/share/mise/bin/mise
Setting env vars
  Setting MISE_LOG_LEVEL=info
  Setting MISE_TRUSTED_CONFIG_PATHS=/home/runner/work/Cosafe-IaC/Cosafe-IaC
  Setting MISE_YES=1
  Adding /home/runner/.local/share/mise/shims to PATH
Running mise --version
  /home/runner/.local/share/mise/bin/mise --version
  [2](https://github.com/cosafe/Cosafe-IaC/actions/runs/11962166151/job/33349939256#step:3:2)024.11.22 linux-x64 (6176d56 202[4](https://github.com/cosafe/Cosafe-IaC/actions/runs/11962166151/job/33349939256#step:3:4)-11-21)
Running mise install 
  /home/runner/.local/share/mise/bin/mise install
  mise plugin:terraform clone https://github.com/asdf-community/asdf-hashicorp.git
  mise plugin:terraform ✓ https://github.com/asdf-community/asdf-hashicorp.git#22eb1c4
  mise ERROR lockfile is experimental. Enable it with `mise settings set experimental true`
  mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
Error: The process '/home/runner/.local/share/mise/bin/mise' failed with exit code 1
```

`.mise/config.toml`

```toml
[tools]
terraform = '1.6.6'
terragrunt = '0.68.8'
```

Relevant part of workflow:

```yaml
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install required tooling
        uses: jdx/mise-action@v2
```

**Comment by BeyondEvil** [comment]
Updating the config with

```toml
[settings]
lockfile = false
```

fixed it.
