### ISSUE TITLE
mise-action always installs latest tuist version causing Tool not installed in workflow

### ISSUE THREAD

**Issue by yasali** [jdx/mise-action#168]
We have been using this flow for a long time to install Tuist without any errors.

```
 - name: Install mise
      if: inputs.install_tuist == 'true'
      uses: jdx/mise-action@v2
      with:
        install: false
        cache: true
    - name: Install Tuist
      if: inputs.install_tuist == 'true'
      run: |
        : Install Tuist
        : # Add `mise doctor` to debug mise installation issues.
        mise install tuist
      shell: bash
```

But since few weeks we have been getting this error,

```
mise ERROR Tool not installed for shim: tuist
Missing tool version: asdf:tuist@4.38.2
Install all missing tools with: mise install
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
make: *** [tug] Error 1
Error: Process completed with exit code 2.
```
We specify tuist version in the .tuist-version files but mise-action is always installing the latest version, because of that we are getting this error. Can any one help what should we do to resolve this issue?
