### ISSUE TITLE
Terraform is missing after installation

### ISSUE THREAD

**Issue by xremming** [jdx/mise-action#175]
For whatever reason, Terraform is missing after installing.

I have tried disabling the cache and running reshim but it just isn't there. Or actually, more annoyingly it is there at least based on the logs but the command just doesn't work. It seems to be missing from the shims directory and for whatever reason reshimming doesn't fix that.

Feels like it's likely an issue with mise itself but I have only seen it appear in GitHub Actions.

**Comment by php-coder** [comment]
I've just used mise and it successfully installs Terraform. My configuration is simple:
```yaml
      - name: Install mise to set up Terraform
        uses: jdx/mise-action@v2.1.11 # https://github.com/jdx/mise-action
        with:
          version: 2025.3.2                  # [default: latest] mise version to install
          install: true                      # [default: true] run `mise install`
          cache: true                        # [default: true] cache mise using GitHub's cache
          log_level: info                    # [default: info] log level
          working_directory: infra/terraform # [default: .] directory to run mise in
```
and
```console
$ cat infra/terraform/mise.toml
[tools]
terraform = "1.11.1"
```
