### ISSUE TITLE
mise installation on windows is faulty

### ISSUE THREAD

**Issue by ssbarnea** [jdx/mise-action#176]
Using this action on Windows does not produce optimal results:

- `unzip` is required but absent by default
- `mise` is installed but not added to the PATH

I found `scoop mise install` as being a much better as it does make mise available right away.

Still, scoop is not installed by default, so additional steps are needed

```yaml
- name: prepare windows host
  if: runner.os == 'Windows'
  shell: pwsh # https://dev.to/pwd9000/github-actions-all-the-shells-581h
  # scoop has big advantages over winget, it's faster unattended and
  # automatically adds the executables to the PATH
  run: |
    if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) { Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force; iwr -useb get.scoop.sh | iex }
    $env:Path += ";$env:USERPROFILE\scoop\shims"
    if (-not (Get-Command mise -ErrorAction SilentlyContinue)) { scoop install mise }
    mise --version
```

Maybe we can look into improving the action to do these?
