### ISSUE TITLE
in CI `mise use` crashes if directory contains `.node-version` only

### ISSUE THREAD

**Issue by y-nk** [jdx/mise-action#178]
### Context
i'm trying to migrate my CI pipeline from purely node/pnpm to mise to support other runtimes (rust, python). we're still using `pnpm` and `package.json` files to find out the version number and which workspaces have been updated. (it'd be so nice if `mise.toml` had monorepo/workspace support)

### Problem
I'm running `mise-action` **twice** in a single action to be able to prep the monorepo like this:

```yaml
    - name: monorepo tooling
      uses: jdx/mise-action@v2
      with:
        cache_key_prefix: monorepo
        experimental: true # for the hooks

    - name: monorepo env
      run: mise env --dotenv >> "$GITHUB_ENV"
      shell: bash

    - if: ${{ inputs.workspace }}
      name: find workspace path
      run: |
        abs=$(pnpm --silent --filter "${{ inputs.workspace }}" exec -- pwd)
        rel=$(echo ${abs} | sed "s|$(pwd)/||g")

        echo "abs=${abs}" >> $GITHUB_OUTPUT
        echo "rel=${rel}" >> $GITHUB_OUTPUT

      id: paths
      shell: bash

    - if: ${{ inputs.workspace }}
      name: workspace tooling
      uses: jdx/mise-action@v2
      with:
        cache_key_prefix: workspace
        experimental: true # for the hooks
        working_directory: ${{ steps.paths.outputs.rel }}

    - if: ${{ inputs.workspace }}
      name: workspace env
      working-directory: ${{ steps.paths.outputs.rel }}
      run: mise env --dotenv >> "$GITHUB_ENV"
      shell: bash

    - if: ${{ inputs.workspace }}
      name: enforce workspace tooling
      working-directory: ${{ steps.paths.outputs.rel }}
      run: mise use
      shell: bash

    - run: echo "result=$(node --version)" >> $GITHUB_OUTPUT
      id: node-version
      shell: bash

    - run: echo "result=$(pnpm --version)" >> $GITHUB_OUTPUT
      id: pnpm-version
      shell: bash

    - run: |
        echo 'setup done for ${{ inputs.workspace || 'root' }} (${{ steps.paths.outputs.abs || '.' }})'
        echo 'node: ${{ steps.node-version.outputs.result }}'
        echo 'pnpm: ${{ steps.pnpm-version.outputs.result }}'
      shell: bash
```

my 1st problem was that the node version installed in the 1st run was still used (`22.14`) even if the 2nd run would install `22.11`. 

<details>
<summary>Github action 1st run screenshot</summary>

![Image](https://github.com/user-attachments/assets/34357596-c10a-40a6-a921-12974e23c9c1)

</details>

So in a 2nd attempt, i thought maybe that i'd need to call `mise use` manually from the workspace directory, so that it'd use the proper version, but it seems `mise use` cannot work when there's only a `.node-version` in the cwd.

<details>
<summary>Github action 2nd run screenshot</summary>

![Image](https://github.com/user-attachments/assets/b85ac3bf-890d-433b-adf5-719826bc1b36)

</details>

I'm not sure how to bypass/fix that. Anybody with pointers?
