### ISSUE TITLE
Ability to install only from the config in the current folder

### ISSUE THREAD

**Issue by php-coder** [jdx/mise-action#183]
Here is my use-case:
1) I have a workflow to execute Terraform
2) Terraform configuration is placed under `infra/terraform` with related `mise.toml`:
```console
$ cat infra/terraform/mise.toml
[tools]
terraform = "1.11.1"
```
3) `mise-action` plugin installs Terraform but it also installs dependencies from a project's root `mise.toml`:
```console
$ cat mise.toml
[tools]
java = "adoptopenjdk-8.0.442"
maven = "3.6.3"
```

Java and Maven is needed to build a project, but not during Terraform execution. I'd like to have a parameter to tell mise to ignore installation from parent directories.

**Comment by php-coder** [comment]
I figured out a solution by myself but it would be nice to have it documented somewhere as I wasn't obvious from the first sight (for instance, I've tried `mise config set settings.disable_tools --type list java,maven` that modified `mise.toml` from current directory and I had to disable auto installation):
```yaml
      - name: Install mise to set up Terraform
        uses: jdx/mise-action@v2.1.11 # https://github.com/jdx/mise-action
        with:
          ... # skipped
        env:
          # Workaround: don't install parent's dependencies as we don't use them
          # See: https://github.com/jdx/mise-action/issues/183
          # https://mise.jdx.dev/configuration/settings.html#disable_tools
          MISE_DISABLE_TOOLS: java,maven
```
