### ISSUE TITLE
Clippy is missing?

### ISSUE THREAD

**Issue by ospfranco** [jdx/mise-action#184]
Hi! Thanks for this action, it's super useful, however, when I try to run, I get a missing tool and a weird toolchain name?

```
Run cargo clippy -p opacity_core --all-features --all-targets -- --no-deps -D warnings
error: 'cargo-clippy' is not installed for the toolchain '1.85.0-x86_64-unknown-linux-gnu'.
To install, run `rustup component add --toolchain 1.85.0-x86_64-unknown-linux-gnu clippy`
Error: Process completed with exit code 1.
```

From the [docs](https://mise.jdx.dev/lang/rust.html#profile) the default profile should contain clippy no? but the `1.85.0-x86_64-unknown-linux-gnu` toolchain doesn't look like something I recognize.

Here is the `yaml` that installs mise:

```yaml
    - uses: jdx/mise-action@v2
      with:
        experimental: true
```

and my `mise.toml`:

```toml
[tools]
bun = "latest"
rust = { version = "latest", targets = "x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim,aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android" }
"cargo:cargo-ndk" = "latest"
"cargo:cargo-set-version" = "latest"

[hooks]
postinstall = "bun install"

[tasks]
build = "bun zx ./scripts/build.mjs"
test = "bun zx ./scripts/test.mjs"
lint = "bun zx ./scripts/lint.mjs"
format = "bun zx ./scripts/format.mjs"
fix = "bun zx ./scripts/fix.mjs"
update-rn = "bun zx ./scripts/update.rn.mjs"
dev-server = "bun run --watch scripts/dev-server.mts"
```

Maybe I need to manually add `x86_64-unknown-linux-gnu` to the targets?
