### ISSUE TITLE
output a dictionary of tool versions

### ISSUE THREAD

**Issue by mhanberg** [jdx/mise-action#30]
## Description

It would be useful to output the versions of each tool that is detected in the .mise.toml/.tool-versions file to use later on in the workflow, while still keeping them isolated to one place.

One example is setting a cache key based on the language version, elixir below

```yaml
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-

```

I believe a workaround is to just hash the .mise.toml file, and whenever you change it, it will bust the cache, but that would bust it even if you change a version of an unrelated (to this cache) tool.

**Comment by jdx** [comment]
I'm not sure if this would be a great idea. There's a lot of things like env vars and settings that would change how tools get installed

**Comment by eproxus** [comment]
I'd like to have something similar. For example, I've done this to detect which versions the Mise action installed:

```yaml
    - name: Install dependencies
      uses: jdx/mise-action@v2

    - id: mise-versions
      shell: bash
      run: mise current | sed 's/ /=/' >> $GITHUB_OUTPUT

    - id: cache-rebar-deps-restore
      uses: actions/cache/restore@v4
      with:
        key: ${{ runner.os }}${{ runner.arch }}-erlang${{ steps.mise-versions.outputs.erlang }}-rebar${{ steps.mise-versions.outputs.rebar }}-${{ hashFiles('rebar.lock') }}
        path: |
          ~/.cache/rebar3
          _build
```

I think it would be useful if the Mise action itself did this (it should just be a static report of what was installed). The above could then be simplified to:

```yaml
    - name: Install dependencies
      id: mise
      uses: jdx/mise-action@v2

    - id: cache-rebar-deps-restore
      uses: actions/cache/restore@v4
      with:
        key: ${{ runner.os }}${{ runner.arch }}-erlang${{ steps.mise.outputs.versions.erlang }}-rebar${{ steps.mise.outputs.versions.rebar }}-${{ hashFiles('rebar.lock') }}
        path: |
          ~/.cache/rebar3
          _build
```
