### ISSUE TITLE
Export environment variables from config

### ISSUE THREAD

**Issue by reitzig** [jdx/mise-action#36]
I want make use of setting environment variables through mise, attempting to replace `direnv` in simple cases at least.

Unfortunately, the action does not export the variables included in the configuration:

[Example config](https://github.com/reitzig/template-goapp/blob/main/.config/mise.toml):
![image](https://github.com/jdx/mise-action/assets/4246780/dadff66b-2cfc-4fbe-8b2b-2bc805467fa6)

[Example workflow](https://github.com/reitzig/template-goapp/actions/runs/7775274422/job/21201067553):
![image](https://github.com/jdx/mise-action/assets/4246780/7a833487-3720-4f41-8f88-b64cc66d6b9d)
The build subsequently fails because changie doesn't find its config.

**Comment by reitzig** [comment]
Workaround:

```yaml
    - uses: jdx/mise-action@v2
      with:
        install: false # we only need env

    - name: Load mise env
      run: |
          mise env -s bash \
              | grep -v 'export PATH=' \
              | cut -d' ' -f2 \
              >> "$GITHUB_ENV"
```
